### PR TITLE
[narwhal] fix cancellation safety for permit and future pattern

### LINKED ISSUE #5137: [narwhal] try_fut_and_permit is not cancellation safe
It seem commonly used try_fut_and_permit (and similar pattern in executor) is broken

The way it works is it calls `join(future_[un]ordered.next(), sender.permit())`

And then this is part of some bigger select with other branches.

Now this `join()` is what can be called 'not cancellation safe' future. (more on this [here](https://docs.rs/tokio/latest/tokio/macro.select.html))

Imagine that first clause of this join(one that polls future_ordered list) resolves and returns some item, but sender does not have permits yet

And then some other branch of select is activated. What will happen? All other futures of select are dropped, *including our join that already has result from future_ordered!*

The other part of join(sender.permit) is drop safe, it will return permit back. But first part will simply discard the result.

### PR DESCRIPTION
**Pull request by andll**
We have a pattern where we need to poll the FuturesUnordered and wait for receiving channel to have a permit at the same time.

It was implemented with `try_fut_and_permit` which introduced `join(permit(), waiting.next()`. This join is not cancellation safe (see #5137 for more details) and will drop the message under load when permit is not available.

This PR fixes cancellation safety by chaining polling for the permit and polling `FuturesUnordered` which is cancellation safe.

To add a bit more flavor here - problem with previous implementation via join() is that join can resolve waiting.next() before permit is available and drops result, which is not safe. Polling permit first is safe because dropping permit 'reverts' the effects. (While dropping result from `FuturesUnordered` does not).

This PR also replaces macro with strongly typed `WithPermit` trait which seems like a more preferred approach - macro basically consumes anything that has method with name `reserve` which is not very sound.

Fixes #5137

### CODE REVIEW

File: narwhal/primary/src/certificate_waiter.rs [hunk 1]
```diff
@@ -149,7 +149,9 @@ impl CertificateWaiter {
                     waiting.push(fut).await;
                 }
                 // we poll the availability of a slot to send the result to the core simultaneously
-                (Some(certificate), permit) = try_fut_and_permit!(waiting.try_next(), self.tx_core) => {
+                Some((permit, Some(certificate))) = self.tx_core.with_permit(waiting.next()) => {
+                        // todo - consider if unwrap is a best action here
+                        let certificate = certificate.unwrap();
```
Comment (bmwill) [inline narwhal/primary/src/certificate_waiter.rs:154]: maybe match on:
```
Some((permit, Some(Some(certificate))))
```

Although i'm not quite sure why they're is a double layer of Options

Comment (andll) [reply narwhal/primary/src/certificate_waiter.rs:154]: So the unwrap below is for Result, not Option, I would prefer not to ignore the error

Comment (bmwill) [reply narwhal/primary/src/certificate_waiter.rs:154]: Well previously the errors were ignored, so unwrapping here may cause an issue and crash the node. Perhaps the best thing to do now would be to log the error and then continue.

**Comment by andll** [comment]
@huitseeker - replied to your PR

File: narwhal/primary/src/certificate_waiter.rs (hunk 1 above)
Comment (andll) [reply narwhal/primary/src/certificate_waiter.rs:154]: If I read code of the macro correctly, it was logging the error and then panic?
```
                tracing::error!("{e}");
                panic!("I/O failure, killing the node.");
```

Comment (andll) [reply narwhal/primary/src/certificate_waiter.rs]: But I think you are right in a sense that it seem more reasonable to log error here rather then panic

**Review by bmwill — APPROVED** [review]

**Comment by bmwill** [comment]
I approved, but lets make sure to include a test to verify that this doesn't have the same problem. Looks like @huitseeker 's test is a good starting point

**Review by huitseeker — APPROVED** [review]
Thanks a lot, this is really awesome!

**Comment by andll** [comment]
Ok, let me merge this and we will continue conversation on the unit test PR
