### PR TITLE
Better network for the consensus client

### LINKED ISSUE #931: Better network for consensus client
The network of the consensus client is not ideal. For instance it should not try to reconnect immediately after the connection fails and instead use some sort of back off. We may also move this logic to `sui-network::transport` to expose a 'stream client' or something like that.

### PR DESCRIPTION
**Pull request by asonnino**
Fix #931

### CODE REVIEW

File: sui_core/src/consensus_client.rs [hunk 1]
```diff
@@ -218,11 +232,66 @@ impl ConsensusClient {
...
         }
     }
 }
+
+/// Make the network client wait a bit before re-attempting network connections.
+pub struct ConnectionWaiter {
+    /// The minimum delay to wait before re-attempting a connection.
+    min_delay: u64,
+    /// The maximum delay to wait before re-attempting a connection.
+    max_delay: u64,
```
Comment (gdanezis) [inline sui_core/src/consensus_client.rs:250]: Is that millis, or seconds?

File: sui_core/src/consensus_client.rs [hunk 2]
```diff
@@ -218,11 +232,66 @@ impl ConsensusClient {
...
+
+    /// Return the number of failed attempts.
+    pub fn status(&self) -> &usize {
+        &self.retry
+    }
+
+    /// Wait for a bit (depending on the number of failed connections).
+    pub async fn wait(&mut self) {
+        if self.delay != 0 {
+            sleep(Duration::from_millis(self.delay)).await;
```
Comment (gdanezis) [inline sui_core/src/consensus_client.rs:282]: Its millis, do put that in the field documentation above

**Review by gdanezis — APPROVED** [review]
LGTM
