### PR TITLE
Fix initialization of next_shared_object_versions

### LINKED ISSUE #5754: Shared object sequencing at beginning of epoch is broken (and owned->shared upgrades broken at all times)
The code at https://github.com/MystenLabs/sui/blob/main/crates/sui-core/src/authority/authority_per_epoch_store.rs#L623 is incorrect:

```
                None => self
                    // TODO: if we use an eventually consistent object store in the future,
                    // we must make this read strongly consistent somehow!
                    .get_latest_parent_entry(*id)?
                    .map(|(objref, _)| objref.1)
                    .unwrap_or_else(|| *initial_shared_version),
```

There are two things happening here, both of which are necessary, but they conflict with each other.

1. When a new validator joins the committee at the beginning of an epoch (or if a returning validator has wiped its sequence tables), it must read the latest version of the object (done here with `get_latest_parent_entry()`) in order to determine what version to assign next. There are two problems with this:
     a. (minor) it assumes the object store allows consistent reads after the end of an epoch.
     b. (major) get_latest_parent_entry may be updated due to a cert being executed via checkpoint sync (`handle_certificate_with_effects`) before the first narwhal message is processed.

2. When an owned object is upgraded to a shared object, we need to use the `initial_shared_version`. But we can't tell that we are in the upgrade path rather than the beginning-of-new-epoch path, so the `initial_shared_version` will never be consulted in the case of an upgrade - which was the entire purpose of having `initial_shared_version`

### PR DESCRIPTION
**Pull request by mystenmark**
Previously, we attempted to initialize `next_shared_object_versions` the first time we sequence a cert that touches a given object. Unfortunately, this will not work if a transaction touching that object has already been executed via checkpoint sync. See the referenced bug below for details.

To fix this, we now initializate `next_shared_object_versions` for a given object _before_ we set the shared locks for that object regardless of whether we are setting the locks in the consensus task or from checkpoint sync. This ensures that, if the object already existed (i.e. was created in a prior epoch) we are guaranteed to read the latest version of the object from the previous checkpoint.

However, because we are now initializing `next_shared_object_versions` from multiple tasks, we need to account for races. Optimistic transactions are used to handle races. When there is a race, one task will succeed in initializing `next_shared_object_versions`, and then other tasks will have to retry, will notice that `next_shared_object_versions` has been initialized already, and will not attempt to write to it again.

Also expose SetSnapshot function of rocksdb transactions.

Fixes #5754

### CODE REVIEW

File: crates/sui-core/src/authority/authority_per_epoch_store.rs [hunk 1]
```diff
@@ -427,14 +428,143 @@ impl AuthorityPerEpochStore {
...
+    ) -> SuiResult<Vec<SequenceNumber>> {
+        do_transaction!({
+            // This code may still be correct without using a transaction snapshot, but I couldn't
+            // convince myself of that.
+            let db_transaction = self
+                .tables
+                .next_shared_object_versions
+                .transaction_with_snapshot()?;
+
+            let next_versions = db_transaction.multi_get(
```
Comment (andll) [inline crates/sui-core/src/authority/authority_per_epoch_store.rs:459]: Should this be `get_for_update` to make sure optimistic locks are put during read, not write?

**Review by andll — APPROVED** [review]
I think this approach should work. I'll spend a bit more time later to poke holes, but going to accept now so that we can merge the change and unblock other work.

If I understand correctly, instead of using `transaction_with_snapshot`, `get_or_init_next_object_versions` could also use MutexTable on `objects_to_init` which would be semantically equivalent?

File: crates/sui-core/src/authority/authority_per_epoch_store.rs (hunk 1 above)
Comment (mystenmark) [reply crates/sui-core/src/authority/authority_per_epoch_store.rs:459]: `transaction_with_snapshot` means you don't have to do that (see: https://github.com/EighteenZi/rocksdb_wiki/blob/master/Transactions.md#setting-a-snapshot) - @phoenix-o and I have been going back and forth on what the best pattern is.

**Comment by mystenmark** [comment]
> If I understand correctly, instead of using transaction_with_snapshot, get_or_init_next_object_versions could also use MutexTable on objects_to_init which would be semantically equivalent?

That would have fixed it as well - I think using transactions is probably going to be better due to how rare conflicting writes will be in practice.
