### PR TITLE
[gas] Fix potential data race in gas object check

### LINKED ISSUE #4597: Potential data race in checking gas object
In transaction input checker, we always check the latest version of the gas object, instead of the gas object specified in the input. This is not idempotent and could lead to data races.

### PR DESCRIPTION
**Pull request by lxfind**
Not sure what conditions would trigger a real problem in prod, fix it just in case.
When checking gas and creating gas meter, we should also make sure we use the requested version instead of latest version.
Resolves #4597

### CODE REVIEW

**Review by mystenmark — APPROVED** [review]
Good find!

File: crates/sui-core/src/transaction_input_checker.rs [hunk 1]
```diff
@@ -90,7 +91,7 @@ where
 #[instrument(level = "trace", skip_all)]
 async fn check_gas<S>(
     store: &SuiDataStore<S>,
-    gas_payment_id: ObjectID,
+    gas_payment: &ObjectRef,
```
Comment (velvia) [inline crates/sui-core/src/transaction_input_checker.rs:94]: Technically the digest isn't necessary and we can just pass the ID and version here.
