### PR TITLE
[move] Avoid stack overflow during tests

### LINKED ISSUE #5583: move integration tests can exceed >2MB stack usage, possibly evading guard page
Please see https://github.com/MystenLabs/sui/pull/5549 for work-around.

Here's a stack trace: https://gist.githubusercontent.com/mystenmark/8c994201e79047708229b6a6f17dcebb/raw/b3bc2a813cef2d77d1e16fdc7081236fb402387d/g - note that this stack is only a few hundred frames deep, yet it exceeded a 2MB limit.

There are several concerning things to investigate
- This is happening for very small, simple source files that shouldn't require very deep recursion.
- It does not appear that the guard page is reliably catching this error. The failing tests do not seem to fail reliably, and prior to https://github.com/MystenLabs/sui/pull/5490 (which should not impact the move tests at all) none of them failed at all.

The main question at this point: is undetected stack overflow happening routinely during move compilation.

### PR DESCRIPTION
**Pull request by amnn**
The move compiler makes heavy use of recursion, and at `opt-level` less than or equal to `1`, some of its stack frames can be ~80KiB in size which can cause compiling relatively simple Move programs to fail with a stack overflow.

Enabling `opt-level = 2` makes a big difference to these stack frames, reducing their size by up to 10x, which alleviates the stack overflows, and also allows us to wind back a previous workaround which involved running tests with (very) large thread stacks (128MiB).

My suspicion (not confirmed) is that the main optimisation helping in this case is one where local variables with non-overlapping lifetimes are allowed to overlap in their use of stack space, which can be especially helpful when the local variables exist along distinct conditional branches or match arms.

We will still eventually want to refactor the compiler not to rely so much on recursion, but this change should make that less urgent.

## Test Plan

Run all tests

```
sui$ cargo simtest --no-fail-fast
sui$ cargo nextest run --no-fail-fast
```

Confirm that the stacktrace within a test that is known to stack overflow contains (much) smaller stack frames:

```
sui$ rust-lldb ./target/debug/deps/sui-core-... test_move_call_mutable_object_not_mutated
(lldb) command script import ./scripts/lldb_frame_sizes.py
(lldb) b move_compiler::hlir::translate::exp_impl
(lldb) b move_compiler::hlir::translate::exp_::exp_loop
(lldb) run
(lldb) frame-sizes
```

### Before

```
     73520B move_compiler::hlir::translate::exp_impl::h6ae8d9cffb6bda2a (translate.rs:1101:34)
     80608B move_compiler::hlir::translate::exp_::exp_loop::h8602552e346e1ddd (translate.rs:1019:29)
      2416B move_compiler::hlir::translate::exp_::h694ef605af4c0906 (translate.rs:1032:5)
     17408B move_compiler::hlir::translate::statement::h62960adc8fa911ed (translate.rs:614:22)
      7088B move_compiler::hlir::translate::block::haa6418b9aef3a15c (translate.rs:570:27)
      ... [snip] ...
```

### After

```
      7360B move_compiler::hlir::translate::exp_impl::hf00087ef9e004e16 (translate.rs:1063:21)
      9824B move_compiler::hlir::translate::exp_::exp_loop::h6affec8d02a5283a (translate.rs:1019:29)
      1392B move_compiler::hlir::translate::exp_::h06753bb8c7bf5628 (translate.rs:1032:5)
      4112B move_compiler::hlir::translate::statement::h9a8095baef2ff771 (translate.rs:640:21)
         0B move_compiler::hlir::translate::block::heec8e8b700447d80 (translate.rs:570:27)
      ... [snip] ...
```

See #6781 for a definition of `frame-sizes`

Closes #5583

### CODE REVIEW

File: crates/sui-core/src/unit_tests/move_integration_tests.rs [hunk 1]
```diff
@@ -28,1847 +28,1793 @@ use std::{env, str::FromStr};
...
-        .build()
-        .unwrap();
-    runtime.block_on(async move {
-        // spawn future on a worker thread with a big stack
-        let handle = tokio::task::spawn(fut);
-        handle.await.unwrap()
-    })
+#[tokio::test]
+#[cfg_attr(msim, ignore)]
+async fn test_object_wrapping_unwrapping() {
```
Comment (amnn) [inline crates/sui-core/src/unit_tests/move_integration_tests.rs:33]: The main change here is no longer wrapping these tests with `run_tokio_test_with_big_stack`, but it shows up as a big diff because of whitespace changes.

**Review by sblackshear — APPROVED** [review]
Excellent fix, thank you Ashok!

File: crates/sui-core/src/unit_tests/move_integration_tests.rs (hunk 1 above)
Comment (rvantonder) [reply crates/sui-core/src/unit_tests/move_integration_tests.rs:33]: You're probably aware but there's always the `Hide whitespace` checkbox in GH that makes this kind of thing more digestible 😄 I often forget to toggle when reviewing PRs

Screen Shot 2022-12-13 at 6 24 34 PM
