### PR TITLE
[CLI] Fix the --dump-bytecode-as-base64 to work with implicit deps

### LINKED ISSUE #21581: --dump-bytecode-as-base64 always fails.
Been using the new version of sui (
sui v1.45.0-3ef5cc5b5c90) on Ubuntu and it would seem it's incompatible with the --dump-bytecode-as-base64 flag. It always errors out like this:

```bash
error[E03001]: address with no value
  ┌─ ./sources/pros.move:3:5
  │
3 │ use sui::url::Url;
  │     ^^^ address 'sui' is not assigned a value

error[E03002]: unbound module
  ┌─ ./sources/pros.move:3:5
  │
3 │ use sui::url::Url;
  │     ^^^^^^^^ Invalid 'use'. Unbound module: 'sui::url'
```

To reproduce, simply spin up a new project using:

```
sui move new <name>
```

And byukd afterwards with:
```
sui move build --dump-bytecode-as-base64
```

Building without the flag works alright though, but my usecase requires the flag be set at build. Any workarounds?

### PR DESCRIPTION
**Pull request by stefan-mysten**
## Description 

The `--dump-bytecode-as-base64` lives in the `sui_commands.rs` in the CLI because of the need to pass in a client to have access to the network. We forgot to add the implicit deps flag there, which this PR fixes.

Should fix and close #21581

## Test plan 

Locally

---

## Release notes

Check each box that your changes affect. If none of the boxes relate to your changes, release notes aren't required.

For each box you select, include information after the relevant heading that describes the impact of your changes that a user might notice and any actions they must take to implement updates. 

- [ ] Protocol: 
- [ ] Nodes (Validators and Full nodes): 
- [ ] gRPC:
- [ ] JSON-RPC: 
- [ ] GraphQL: 
- [ ] CLI: 
- [ ] Rust SDK:

### CODE REVIEW

**Review by wlmyng — APPROVED** [review]

File: crates/sui/src/sui_commands.rs [hunk 1]
```diff
@@ -519,8 +519,10 @@ impl SuiCommand {
                         };
 
                         let rerooted_path = move_cli::base::reroot_path(package_path.as_deref())?;
-                        let build_config =
+                        let mut build_config =
                             resolve_lock_file_path(build_config, Some(&rerooted_path))?;
+                        build_config.implicit_dependencies =
+                            implicit_deps(latest_system_packages());
```
Comment (amnn) [inline crates/sui/src/sui_commands.rs:525]: Shouldn't we be using the `client` above to figure out which version of the system packages to use as implicit deps here?

**Review by amnn — COMMENTED** [review]
Thanks for the quick fix -- but I think we need to do something more sophisticated here, seeing as `--dump-bytecode-as-base64` is really a publish/upgrade flow disguised as a build flow (take a look at the inline comment) (cc @mdgeorge4153 to confirm).

Once we're satisfied and this has landed, let's also cherry-pick it into testnet.

Thanks!

File: crates/sui/src/sui_commands.rs (hunk 1 above)
Comment (stefan-mysten) [reply crates/sui/src/sui_commands.rs:525]: Well, in the original `sui-move` code it is like this, so naively I thought that's what we need to do. I think you're right though (though really confusing as to why `sui move build` and `sui move build --dump` would have slightly different semantics)
https://github.com/stefan-mysten/sui/blob/834c51dbac0b15cd933588e61df5d95c2e527c04/crates/sui-move/src/build.rs?plain=1#L66

Comment (mdgeorge4153) [reply crates/sui/src/sui_commands.rs:525]: Really `sui move build --dump` should be `sui client publish --but-dump-instead`. But I agree it's confusing. I still think the right thing to do is to use a client as @amnn  suggests

**Review by mdgeorge4153 — APPROVED** [review]
