### PR TITLE
[move] Fix vfs relativization

### LINKED ISSUE #16906: Failed to build Move modules
## Steps to Reproduce Issue

I had some errors when trying to build the project:
Failed to build Move modules: Failed to resolve dependencies for package 'test'

e.g.
1. choco install sui
2. sui move new test
3. cd test && sui move build

## Expected Result

Successful

## Actual Result

```
UPDATING GIT DEPENDENCY https://github.com/MystenLabs/sui.git
Failed to build Move modules: Failed to resolve dependencies for package 'test'

Caused by:
    0: Fetching 'Sui'
    1: Failed to reset to latest Git state 'framework/testnet' for package 'Sui', to skip set --skip-fetch-latest-git-deps | Exit status: exit code: 128.
```

## System Information

* OS: Windows 11
* Compiler: sui 1.21.1-5f2bfb1-dirty
* sui client active-env: testnet
* rustup -V: rustup 1.27.0 (bbb9276d2 2024-03-08)
* git -v: git version 2.41.0.windows.3

### PR DESCRIPTION
**Pull request by tnowacki**
## Description 

- pathdiff did not seem to handle windows paths very well, at least in conjunction with the way VFS was converting them to a string
- Should fix #16906

## Test Plan 

- Built on windows

---
If your changes are not user-facing and do not break anything, you can skip the following section. Otherwise, please briefly describe what has changed under the Release Notes section.

### Type of Change (Check all that apply)

- [ ] protocol change
- [X] user-visible impact
- [ ] breaking change for a client SDKs
- [ ] breaking change for FNs (FN binary must upgrade)
- [ ] breaking change for validators or node operators (must upgrade binaries)
- [ ] breaking change for on-chain data layout
- [ ] necessitate either a data wipe or data migration

### Release notes

Fixed issues with `sui move` not working in `cmd.exe` on Windows.

### CODE REVIEW

File: external-crates/move/crates/move-compiler/src/command_line/compiler.rs [hunk 1]
```diff
@@ -347,7 +339,7 @@ impl Compiler {
 
         source_text
             .iter_mut()
-            .for_each(|(_, (path, _))| *path = relativize_path(&vfs_root, *path));
+            .for_each(|(_, (path, _))| *path = vfs_to_original_path[path]);
```
Comment (awelc) [inline external-crates/move/crates/move-compiler/src/command_line/compiler.rs:342]: This map access should not be unconditional as new paths can be generated between when the map is initialized and when it's used here, so not every path will have an entry in the map.

Comment (tnowacki) [reply external-crates/move/crates/move-compiler/src/command_line/compiler.rs]: yeah I found out as much from tests. Attempting to fix but it might blow up on windows

File: external-crates/move/crates/move-compiler/src/command_line/compiler.rs [hunk 2]
```diff
@@ -143,18 +146,37 @@ impl Compiler {
                         .map(|(k, v)| (k.into(), v))
                         .collect::<NamedAddressMap>(),
                 );
+                let paths: Vec<Symbol> = if vfs_root.is_none() {
+                    let paths: Vec<_> = paths.into_iter().map(|p| p.into()).collect();
+                    let paths: Vec<_> = paths.iter().map(|p| p.as_str()).collect();
+                    find_filenames_and_keep_specified(&paths, &mut find_move_files)?
```
Comment (tnowacki) [inline external-crates/move/crates/move-compiler/src/command_line/compiler.rs:152]: In general, I want to get the compiler out of the business of finding files. It is a relic from before the package system.  But its functionality is relied on a bit too much to rip out from this PR, though I totally can if y'all want me to.

File: external-crates/move/crates/move-compiler/src/command_line/compiler.rs [hunk 3]
```diff
@@ -756,46 +785,26 @@ fn generate_interface_files_for_deps(
     Ok(())
 }
 
+// TODO this should really be done by the package system, with the interface files stuffed into the
+// build/ directory for the package. This would give a more consistent location for errors.
```
Comment (tnowacki) [inline external-crates/move/crates/move-compiler/src/command_line/compiler.rs:789]: Speaking of pre-package system relics... it would be really great to make this a package system feature someday

File: external-crates/move/crates/move-package/src/compilation/build_plan.rs [hunk 4]
```diff
@@ -68,9 +69,16 @@ impl BuildPlan {
...
             resolution_graph,
+            compiler_vfs_root: None,
         })
     }
 
+    pub fn set_compiler_vfs_root(mut self, vfs_root: VfsPath) -> Self {
+        assert!(self.compiler_vfs_root.is_none());
+        self.compiler_vfs_root = Some(vfs_root);
+        self
+    }
```
Comment (tnowacki) [inline external-crates/move/crates/move-package/src/compilation/build_plan.rs:80]: I find this very unsatisfying, but am unsure what to do.

File: external-crates/move/crates/move-compiler/src/command_line/compiler.rs [hunk 5]
```diff
@@ -317,17 +316,43 @@ impl Compiler {
...
+                let original = p.path;
+                let vfs = p.to_vfs_path(&vfs_root)?;
+                vfs_to_original_path.insert(Symbol::from(vfs.path.as_str()), original);
+                Ok(vfs)
+            })
             .collect::<Result<Vec<_>, anyhow::Error>>()?;
 
+        for path in targets.iter().chain(&deps) {
+            if !path.path.is_file().unwrap_or(false) {
+                debug_assert!(
```
Comment (awelc) [inline external-crates/move/crates/move-compiler/src/command_line/compiler.rs:343]: Do we need the assertion since we are bailing anyways?

**Review by awelc — APPROVED** [review]
Other than a nit, LGTM

File: external-crates/move/crates/move-compiler/src/command_line/compiler.rs (hunk 2 above)
Comment (cgswords) [reply external-crates/move/crates/move-compiler/src/command_line/compiler.rs:152]: I'm a very large fan of ripping it out as soon as possible.

File: external-crates/move/crates/move-compiler/src/command_line/compiler.rs [hunk 6]
```diff
@@ -317,17 +316,43 @@ impl Compiler {
...
         let targets = targets
             .into_iter()
-            .map(|p| Ok(p.to_vfs_path(&vfs_root)?))
+            .map(|p| {
+                let original = p.path;
+                let vfs = p.to_vfs_path(&vfs_root)?;
+                vfs_to_original_path.insert(Symbol::from(vfs.path.as_str()), original);
+                Ok(vfs)
+            })
             .collect::<Result<Vec<_>, anyhow::Error>>()?;
```
Comment (cgswords) [inline external-crates/move/crates/move-compiler/src/command_line/compiler.rs:329]: Something to mention is there were some build issues in migration where two packages pointed to the same dependency via different relative paths, and those got reported as conflicting even though they were the same. I don't think we should fix that in this PR, but I suspect it may impact some of this code.

File: external-crates/move/crates/move-command-line-common/src/files.rs [hunk 7]
```diff
@@ -121,6 +121,21 @@ pub fn find_move_filenames(
...
+pub fn find_filenames_and_keep_specified<Predicate: FnMut(&Path) -> bool>(
+    paths: &[impl AsRef<Path>],
+    is_file_desired: Predicate,
+) -> anyhow::Result<Vec<String>> {
+    let (file_paths, other_paths): (Vec<&Path>, Vec<&Path>) =
+        paths.iter().map(|p| p.as_ref()).partition(|s| s.is_file());
+    let mut files = file_paths
+        .into_iter()
+        .map(path_to_string)
+        .collect::<anyhow::Result<Vec<String>>>()?;
```
Comment (cgswords) [inline external-crates/move/crates/move-command-line-common/src/files.rs:134]: Should these be filtered by `is_file_desired`?

File: external-crates/move/crates/move-package/src/compilation/build_plan.rs (hunk 4 above)
Comment (cgswords) [reply external-crates/move/crates/move-package/src/compilation/build_plan.rs:80]: This could be `std::mem::replace` where you hand back the old one and make the caller deal with it

**Review by cgswords — APPROVED** [review]
Approved, modulo the nit above and a few small questions.

File: external-crates/move/crates/move-compiler/src/command_line/compiler.rs (hunk 5 above)
Comment (tnowacki) [reply external-crates/move/crates/move-compiler/src/command_line/compiler.rs:343]: I want the assertion so we get a panic instead of an Err in debug builds

File: external-crates/move/crates/move-command-line-common/src/files.rs (hunk 7 above)
Comment (tnowacki) [reply external-crates/move/crates/move-command-line-common/src/files.rs:134]: No, the intention of this function versus find_files is to keep any file specified.
