### PR TITLE
Fix shared object retries

### LINKED ISSUE #4387: Shared object transactions may never finish the full execution flow
Consider the following scenario: a shared object transaction certificate is being executed, and is able to finish execution and update new object state into db. However before committing effects, the connection is dropped. Latter we would attempt to re-execute this transaction, but then in transaction_input_checker, for shared objects, we only load the latest version, and in this case we would be loading the updated object instead of the object that's supposed to be used in the transaction. Then we check shared object locks, and here we would fail because it will detect that the object version doesn't match with the locked version. The consequence is that we will never be able to finish executing this transaction and never have the effects stored.

### PR DESCRIPTION
**Pull request by mystenmark**
Fixes #4387 

The basic idea here is that transaction_input_check should always load the object versions that will be consumed by the TX, rather than the latest versions in the DB. This behavior comes for free with owned objects, since those are already specified by ObjRef. By using the shared lock table, we provide the same behavior for shared objects.

### CODE REVIEW

**Review by lxfind — APPROVED** [review]
Could consider renaming `get_input_objects` in the store to something like `get_latest_objects` or similar

**Comment by mystenmark** [comment]
> Could consider renaming `get_input_objects` in the store to something like `get_latest_objects` or similar

As discussed in slack, this would be misleading, since it doesn't actually get the latest objects in the case of owned objects.

File: crates/sui-core/src/authority/authority_store.rs [hunk 1]
```diff
@@ -354,6 +354,31 @@ impl<S: Eq + Debug + Serialize + for<'de> Deserialize<'de>> SuiDataStore<S> {
...
+    ) -> Result<Vec<Option<Object>>, SuiError> {
+        let shared_locks: HashMap<_, _> = self.all_shared_locks(digest)?.into_iter().collect();
+
+        let mut result = Vec::new();
+        for kind in objects {
+            let obj = match kind {
+                InputObjectKind::MovePackage(id) => self.get_object(id)?,
+                InputObjectKind::SharedMoveObject(id) => match shared_locks.get(id) {
+                    Some(version) => self.get_object_by_key(id, *version)?,
+                    None => None,
```
Comment (andll) [inline crates/sui-core/src/authority/authority_store.rs:371]: I think this should be something like `shared_locks.get(id).expect("Did not find shared lock for shared object")` right?
Since this is basically an invariant violation, we should not just return None
