### PR TITLE
[move-compiler] Fix more issues with decl field indicies

### LINKED ISSUE #25548: Compiler panic in match exhaustiveness: `unwrap()` on field lookup in `order_fields_by_decl()`
The compiler panics with `unwrap()` on `None` in [`shared/matching.rs:937`](https://github.com/MystenLabs/sui/blob/1a27af4bf7ea29b0058c4d5b19ccc98f963f9b2e/external-crates/move/crates/move-compiler/src/shared/matching.rs#L937) in `order_fields_by_decl()`.

The crash appears when a `match` arm uses a positional struct pattern (e.g. `P(false)`) against a named struct object (e.g. `N { x: bool }`), the typing pass emits a type error but continues into match exhaustiveness analysis.

MRE:
```move
module 0x42::m {
    public struct P(bool) has drop;
    public struct N { x: bool } has drop;

    fun f(n: N): bool {
        match (n) {
            P(false) => false,
        }
    }
}
```

Reproduce steps:
```
cd external-crates/move
cargo +nightly run --release -p move-compiler --bin move-check -- mre/mre_shared_matching_937.move
```

Output:
```
thread '<unnamed>' panicked at crates/move-compiler/src/shared/matching.rs:937:57:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Expected behavior: a type-error diagnostic about the mismatched struct kind in the pattern, not a compiler panic.

Git commit: 1a27af4bf7ea29b0058c4d5b19ccc98f963f9b2e
Build: release
cargo 1.91.0-nightly (840b83a10 2025-07-30)
rustc 1.91.0-nightly (3672a55b7 2025-08-13)

### PR DESCRIPTION
**Pull request by tnowacki**
## Description 

- Fixes issue introduced in #25525 (whoops)
- Adds missing test from #25525 (whoops)
- Fixes usage of the context in matching
- Fixes #25548 in the same manner as #25525

## Test plan 

- New tests

---

## Release notes

Check each box that your changes affect. If none of the boxes relate to your changes, release notes aren't required.

For each box you select, include information after the relevant heading that describes the impact of your changes that a user might notice and any actions they must take to implement updates. 

- [ ] Protocol: 
- [ ] Nodes (Validators and Full nodes): 
- [ ] gRPC:
- [ ] JSON-RPC: 
- [ ] GraphQL: 
- [ ] CLI: 
- [ ] Rust SDK:
- [ ] Indexing Framework:

### CODE REVIEW

File: external-crates/move/crates/move-compiler/src/shared/matching.rs [hunk 1]
```diff
@@ -154,14 +154,13 @@ impl PatternArm {
             .all(|pat| matches!(pat.pat.value, TP::Wildcard | TP::Binder(_, _)))
     }
 
-    fn all_wild_arm<'env>(
+    fn all_wild_arm<const AFTER_TYPING: bool, MC: MatchContext<AFTER_TYPING>>(
```
Comment (cgswords) [inline external-crates/move/crates/move-compiler/src/shared/matching.rs:157]: Ouch. Thanks!

**Review by cgswords — APPROVED** [review]
LGTM
