### PR TITLE
[cli] Try to fix the `sui-move-build --dump-bytecode-as-base64 --ignore-chain`

### LINKED ISSUE #21846: Sui CLI fails building bytecode offline even with `--ignore-chain`
Getting the following error when running the `sui` CLI (`testnet-v1.47.0`)

## Steps to Reproduce Issue

With any package:
```
sui move build --dump-bytecode-as-base64 --ignore-chain -p ...
`sui move build --dump-bytecode-as-base64` requires a connection to the network. Current active network is localnet but failed to connect to it.
```
This of course requires an active environment (named 'localnet' in the example above) for which the fullnode RPC is unreachable. 

I specified the dependencies fully, i.e., including `Sui`, `MoveStdLib` and other 'native' dependencies.

The docs say that one should be able to run this command offline
```
      --ignore-chain
          Don't specialize the package to the active chain when dumping bytecode as Base64. This
          allows building to proceed without a network connection or active environment, but it will
          not be able to automatically determine the addresses of its dependencies
```

## Expected Result

The usual JSON produced by `--dump-bytecode-as-base64` (with "dependencies", "digest", and "modules" keys)

## System Information

I ran the above using the `mysten/sui-tools:testnet-v1.47.0` Docker image

### PR DESCRIPTION
**Pull request by stefan-mysten**
## Description 

This PR tries to fix a bug in the `sui move build --dump-bytecode-as-base64 --ignore-chain` as the previous code did not correctly account for `--ignore-chain` flag. The main issue is that when `--ignore-chain` is used, the tree shaking algorithm will not work anymore.

Should fix #21846 

## Test plan 

How did you test the new or updated feature?

---

## Release notes

Check each box that your changes affect. If none of the boxes relate to your changes, release notes aren't required.

For each box you select, include information after the relevant heading that describes the impact of your changes that a user might notice and any actions they must take to implement updates. 

- [ ] Protocol: 
- [ ] Nodes (Validators and Full nodes): 
- [ ] gRPC:
- [ ] JSON-RPC: 
- [ ] GraphQL: 
- [ ] CLI: 
- [ ] Rust SDK:

### CODE REVIEW

File: crates/sui/src/sui_commands.rs [hunk 1]
```diff
@@ -498,33 +498,43 @@ impl SuiCommand {
...
-
-                        if let Err(e) = client.check_api_version() {
-                            eprintln!("{}", format!("[warning] {e}").yellow().bold());
-                        }
-
-                        let chain_id = if build.ignore_chain {
+                        let (chain_id, client) = if build.ignore_chain {
                             // for tests it's useful to ignore the chain id!
-                            None
+                            (None, None)
```
Comment (mdgeorge4153) [inline crates/sui/src/sui_commands.rs:503]: Might be worth printing a warning in this case that (a) we're using the latest known versions of the implicit dependencies, and (b) the resulting binary will have more dependencies because of the `--ignore-chain`?

**Review by mdgeorge4153 — APPROVED** [review]
Stamp
