### PR TITLE
[zksend] Update garphql query, and use getstashed.com as claim api host

### LINKED ISSUE #20222: [ZkSend] Failed to load created links
## Steps to Reproduce Issue

```
  const res = await listCreatedLinks({
    address: 0xe98aeb0cb3d7d96da47cc5c59c0e3f720dcfe55c625b6005905bbf5ab7a03a50,
    network: "testnet",
    client: suiClient,
  });
```

## Expected Result

the list of links

## Actual Result

throws with ```Failed to load created links```
Reason: A scan limit must be specified for the given filter combination

## System Information

* OS: <specify OS version>
* Compiler: <specify compiler version>

### PR DESCRIPTION
**Pull request by hayes-mysten**
## Description 

fixes #20222 

Describe the changes or additions included in this PR.

## Test plan 

How did you test the new or updated feature?

---

## Release notes

Check each box that your changes affect. If none of the boxes relate to your changes, release notes aren't required.

For each box you select, include information after the relevant heading that describes the impact of your changes that a user might notice and any actions they must take to implement updates. 

- [ ] Protocol: 
- [ ] Nodes (Validators and Full nodes): 
- [ ] Indexer: 
- [ ] JSON-RPC: 
- [ ] GraphQL: 
- [ ] CLI: 
- [ ] Rust SDK:
- [ ] REST API:

### CODE REVIEW

File: sdk/zksend/src/links/list-created-links.ts [hunk 1]
```diff
@@ -16,7 +16,7 @@ const ListCreatedLinksQuery = graphql(`
 		transactionBlocks(
 			last: 10
 			before: $cursor
-			filter: { sentAddress: $address, function: $function, kind: PROGRAMMABLE_TX }
+			filter: { sentAddress: $address, function: $function }
```
Comment (hayes-mysten) [inline sdk/zksend/src/links/list-created-links.ts:19]: The kind filter now causes the GraphQL query to fail, but no address should actually have other kinds of transactions, so it wasn't necessary in the first place
