### PR TITLE
[move][move-compiler] Fix #25349

### LINKED ISSUE #25349: Compiler panic in typing pass: `unwrap()` on `None` for string literal in `match` pattern
I was generating random Move programs to test a Move security tool I'm building and got stuck with this crash.

Is this a bug in the typechecker or expected behavior?

MRE:
```move
module 0x1::m {
    fun f(x: vector<u8>) {
        match (x) {
            "a" => {},
            _ => {},
        };
    }
}
```

Reproduce steps:
```
cargo +nightly run --release -p move-compiler --bin move-check -- inferred_string_match.move
```

Output:
```
    Finished `release` profile [optimized] target(s) in 0.38s
     Running `target/release/move-check poc_inferred_string_match.move`

thread '<unnamed>' (651255) panicked at crates/move-compiler/src/typing/translate.rs:2564:41:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Expected behavior: successful compilation or typechecker error. 

Git commit: 1a27af4bf7ea29b0058c4d5b19ccc98f963f9b2e
Build: release
cargo 1.91.0-nightly (840b83a10 2025-07-30)
rustc 1.91.0-nightly (3672a55b7 2025-08-13)

### PR DESCRIPTION
**Pull request by cgswords**
## Description 

Carve out exception to refuse string literals in matching. This fixes #25349 where it was crashing, though long-term supporting something here might be preferred.

## Test plan 

New test added.

---

## Release notes

Check each box that your changes affect. If none of the boxes relate to your changes, release notes aren't required.

For each box you select, include information after the relevant heading that describes the impact of your changes that a user might notice and any actions they must take to implement updates. 

- [ ] Protocol: 
- [ ] Nodes (Validators and Full nodes): 
- [ ] gRPC:
- [ ] JSON-RPC: 
- [ ] GraphQL: 
- [ ] CLI: 
- [ ] Rust SDK:
- [ ] Indexing Framework:

### CODE REVIEW

File: external-crates/move/crates/move-compiler/src/typing/translate.rs [hunk 1]
```diff
@@ -2558,6 +2558,12 @@ fn match_pattern_(
             let x_ty = context.get_local_type(&x);
             T::pat(x_ty, sp(loc, TP::Binder(mut_, x)))
         }
+        P::Literal(sp!(_, Value_::InferredString(_))) => {
+            let msg = "String literals are not currently supported in match patterns";
+            context.add_diag(diag!(TypeSafety::InvalidString, (loc, msg)));
```
Comment (tnowacki) [inline external-crates/move/crates/move-compiler/src/typing/translate.rs:2563]: Could also put feature not supported here if we want?

Comment (cgswords) [reply external-crates/move/crates/move-compiler/src/typing/translate.rs:2563]: That feature issue should have already happened during parsing.
