### PR TITLE
[core] Fix consensus adaptor mem leak + edge-case correctness

### LINKED ISSUE #3130: Investigate memory growth in the Consensus Listnener
The memory profiling run of @velvia in https://github.com/MystenLabs/sui/issues/2974#issuecomment-1179446001 points at a long-lived allocation in the `ConsensusListener`.

This occurs in the memory scenario investigated in #2889, or more exactly in its local reproduction (node restart).
It seems the pending transactions to consensus could be accumulating there indefinitely, and not be cleaned up upon a timeout for a shared object transaction.

This could create a gradual memory consumption buildup at the Sui node. The issue should be confirmed / infirmed (@velvia ) and addressed if necessary (@asonnino ).

### PR DESCRIPTION
**Pull request by gdanezis**
This fixes #3130.

The current design of the consensus listener suffered from two downsides:
- it required an explicit message to be sent to clean up its struts, which may not be sent if a future is just dropped.
- it picked the latest notifier and dropped it, which under retransmission may not be the one that is not more waiting.

We now pass in an explicit channel that we use to notify the consensus listener when the task that awaits a response is dropped, or no more needs to be signal, and use that to clean up structures. We also find the exact channel to drop (by using an id) and remove just that.

### CODE REVIEW

File: crates/sui-core/src/consensus_adapter.rs [hunk 1]
```diff
@@ -49,13 +49,54 @@ type SerializedTransactionInfoResponse = Vec<u8>;
 
 /// Channel to notify the caller when the Sui certificate has been sequenced.
 type TxSequencedNotifier = oneshot::Sender<SuiResult<SerializedTransactionInfoResponse>>;
+type TxSequencedNotifierClose = oneshot::Sender<()>;
 
 /// Message to notify the consensus listener that a new transaction has been sent to consensus
 /// or that the caller timed out on a specific transaction.
 #[derive(Debug)]
 pub enum ConsensusListenerMessage {
```
Comment (asonnino) [inline crates/sui-core/src/consensus_adapter.rs:57]: Shouldn't this be a simple struct?

File: crates/sui-core/src/consensus_adapter.rs [hunk 2]
```diff
@@ -198,31 +239,41 @@ impl ConsensusListener {
...
+                        ConsensusListenerMessage::New(transaction, (replier, mut _closer)) => {
                             let digest = Self::hash_serialized_transaction(&transaction);
                             if self.pending.len() < self.max_pending_transactions {
-                                self.pending.entry(digest).or_insert_with(Vec::new).push(replier);
+                                let id = id_counter;
+                                id_counter += 1;
+
+                                // let len = self.pending.len();
+                                let list = self.pending.entry(digest).or_insert_with(Vec::new);
+                                // println!("Insert {} - {}", len, list.len());
```
Comment (asonnino) [inline crates/sui-core/src/consensus_adapter.rs:261]:
```suggestion
```

File: crates/sui-core/src/consensus_adapter.rs [hunk 3]
```diff
@@ -198,31 +239,41 @@ impl ConsensusListener {
...
                         // Keep track of this certificates so we can notify the user later.
-                        ConsensusListenerMessage::New(transaction, replier) => {
+                        ConsensusListenerMessage::New(transaction, (replier, mut _closer)) => {
                             let digest = Self::hash_serialized_transaction(&transaction);
                             if self.pending.len() < self.max_pending_transactions {
-                                self.pending.entry(digest).or_insert_with(Vec::new).push(replier);
+                                let id = id_counter;
+                                id_counter += 1;
+
+                                // let len = self.pending.len();
```
Comment (asonnino) [inline crates/sui-core/src/consensus_adapter.rs:259]:
```suggestion
```

File: crates/sui-core/src/consensus_adapter.rs (hunk 2 above)
Comment (asonnino) [inline crates/sui-core/src/consensus_adapter.rs:261]:
```suggestion
```

File: crates/sui-core/src/consensus_adapter.rs [hunk 4]
```diff
@@ -116,8 +157,11 @@ impl ConsensusAdapter {
         let bytes = Bytes::from(serialized.clone());
 
         // Notify the consensus listener that we are expecting to process this certificate.
-        let (sender, receiver) = oneshot::channel();
-        let consensus_input = ConsensusListenerMessage::New(serialized.clone(), sender);
+        // let (sender, receiver) = oneshot::channel();
```
Comment (asonnino) [inline crates/sui-core/src/consensus_adapter.rs:160]:
```suggestion
```

File: crates/sui-core/src/consensus_adapter.rs [hunk 5]
```diff
@@ -49,13 +49,54 @@ type SerializedTransactionInfoResponse = Vec<u8>;
...
 /// or that the caller timed out on a specific transaction.
 #[derive(Debug)]
 pub enum ConsensusListenerMessage {
-    New(SerializedConsensusTransaction, TxSequencedNotifier),
-    Cleanup(SerializedConsensusTransaction),
+    New(
+        SerializedConsensusTransaction,
+        (TxSequencedNotifier, TxSequencedNotifierClose),
+    ),
+    // Cleanup(SerializedConsensusTransaction),
```
Comment (asonnino) [inline crates/sui-core/src/consensus_adapter.rs:62]:
```suggestion
```

File: crates/sui-core/src/consensus_adapter.rs [hunk 6]
```diff
@@ -231,13 +282,29 @@ impl ConsensusListener {
...
                                 debug!("No replier to listen to consensus output {digest}");
                             }
                         }
                     }
                 }
+
+                Some((digest, id)) = closed_notifications.next() => {
+                    let should_delete = if let Some(list) = self.pending.get_mut(&digest) {
+                        // First clean up the list
+                        list.retain(|(item_id, _)| *item_id != id);
```
Comment (asonnino) [inline crates/sui-core/src/consensus_adapter.rs:296]: Should we use an HashMap rather than a Vec?

File: crates/sui-core/src/consensus_adapter.rs [hunk 7]
```diff
@@ -328,12 +395,12 @@ impl CheckpointConsensusAdapter {
...
     async fn waiter<T>(
-        receiver: oneshot::Receiver<SuiResult<SerializedTransactionInfoResponse>>,
+        receiver: ConsensusWaiter,
         retry_delay: Duration,
         deliver: T,
     ) -> (SuiResult<SerializedTransactionInfoResponse>, T) {
-        let outcome = match timeout(retry_delay, receiver).await {
-            Ok(reply) => reply.expect("Failed to read back from consensus listener"),
+        let outcome = match timeout(retry_delay, receiver.wait_for_result()).await {
+            Ok(reply) => reply, // .expect("Failed to read back from consensus listener"),
```
Comment (asonnino) [inline crates/sui-core/src/consensus_adapter.rs:403]:
```suggestion
            Ok(reply) => reply,
```

**Review by asonnino — APPROVED** [review]
Much better indeed

File: crates/sui-core/src/consensus_adapter.rs (hunk 6 above)
Comment (gdanezis) [reply crates/sui-core/src/consensus_adapter.rs:296]: This is usually 1-2 elements, so I do not think that a HashMap is really needed here.

File: crates/sui-core/src/consensus_adapter.rs (hunk 1 above)
Comment (gdanezis) [reply crates/sui-core/src/consensus_adapter.rs:57]: Yeah, but the only thing we would do with the structure is break it up again, so I am skipping it right now.
