### PR TITLE
Fix a bug where transfer sui with insufficient gas still lead the object to be transferred

### LINKED ISSUE #3632: Sui Object transferred even when there is insufficient gas

### PR DESCRIPTION
**Pull request by lxfind**
When there is an error due to insufficient gas, we clear the temporary store.
However, in code latter we deduct and update gas on the old object before we cleared the temporary store, and write it into the store. This essentially override the cleared state.
This part of the code is not very clean and probably worth some refactoring to make it less error prone.
This PR resolves #3632.

### CODE REVIEW

File: crates/sui-core/src/unit_tests/gas_tests.rs [hunk 1]
```diff
@@ -156,6 +157,36 @@ async fn test_native_transfer_gas_price_is_used() {
...
+    let tx = Transaction::new(data, signature);
+
+    let effects = send_and_confirm_transaction(&authority_state, tx)
+        .await
+        .unwrap()
+        .signed_effects
+        .unwrap()
+        .effects;
+    // We expect this to fail due to insufficient gas.
+    assert!(effects.status.is_err());
```
Comment (tnowacki) [inline crates/sui-core/src/unit_tests/gas_tests.rs:185]: Should we check what error is given?
