### PR TITLE
[move-compiler] Fix two crashes with macros

### LINKED ISSUE #25456: Compiler panic in naming pass: `debug_assert` fires for `$`-prefixed identifier in `let mut`
The compiler panics with a `debug_assert` failure in [`naming/translate.rs:4028`](https://github.com/MystenLabs/sui/blob/1a27af4bf7ea29b0058c4d5b19ccc98f963f9b2e/external-crates/move/crates/move-compiler/src/naming/translate.rs#L4028) when `let mut $x` (a syntax identifier in bind position) passes through the parser but hits a naming pass assertion.

The parser allows `let mut $<ident>` (dollar-prefixed identifiers) in bind position, but the naming pass assumes this syntax is rejected during parsing and fires `debug_assert!` with `"ICE this should fail during parsing"`.

**Note:** this only reproduces in debug builds.

MRE:
```move
module 0x0::M {
    fun f() {
        let mut $x = 0;
    }
}
```

Reproduce steps:
```
cd external-crates/move
cargo +nightly run -p move-compiler --bin move-check -- mre/mre_naming_translate_4028.move
```

Output:
```
thread 'main' panicked at crates/move-compiler/src/naming/translate.rs:4028:21:
ICE this should fail during parsing
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Expected behavior: a parse error diagnostic about invalid identifier syntax.

Git commit: 1a27af4bf7ea29b0058c4d5b19ccc98f963f9b2e
Build: debug
cargo 1.91.0-nightly (840b83a10 2025-07-30)
rustc 1.91.0-nightly (3672a55b7 2025-08-13)

### PR DESCRIPTION
**Pull request by tnowacki**
## Description 

- Fixes #25456 by simply skipping over the binding
- #25472 is a bit trickier in that it is a bit convoluted. And results from the edge case of this sort of `UnresolvedError` showing up in `make_bindings` for named blocks (and presumably other control flow structures)

## Test plan 

- New tests

---

## Release notes

Check each box that your changes affect. If none of the boxes relate to your changes, release notes aren't required.

For each box you select, include information after the relevant heading that describes the impact of your changes that a user might notice and any actions they must take to implement updates. 

- [ ] Protocol: 
- [ ] Nodes (Validators and Full nodes): 
- [ ] gRPC:
- [ ] JSON-RPC: 
- [ ] GraphQL: 
- [ ] CLI: 
- [ ] Rust SDK:
- [ ] Indexing Framework:

### CODE REVIEW

File: external-crates/move/crates/move-compiler/src/naming/translate.rs [hunk 1]
```diff
@@ -4039,18 +4039,26 @@ fn lvalue(
...
-                    );
-                    let msg = format!(
-                        "Cannot assign to argument for parameter '{}'. \
-                        Arguments must be used in value positions",
-                        v.0
-                    );
-                    let mut diag = diag!(TypeSafety::CannotExpandMacro, (loc, msg));
-                    diag.add_note(ASSIGN_SYNTAX_IDENTIFIER_NOTE);
-                    context.add_diag(diag);
+                    match case {
```
Comment (tnowacki) [inline external-crates/move/crates/move-compiler/src/naming/translate.rs:4042]: This fix seems simple enough

File: external-crates/move/crates/move-compiler/src/hlir/translate.rs [hunk 2]
```diff
@@ -2230,7 +2234,17 @@ fn make_assignments(
...
+        let a_ty = match rvalue.ty.value.type_at_index(idx) {
+            Some(ty) => ty,
+            None => {
+                // we can only get here if the rvalue was malformed and somewhere has an unresolved
+                // error
+                debug_assert!(context.env.has_errors());
+                error_ty = error_single_type(a.loc);
+                &error_ty
+            }
+        };
```
Comment (tnowacki) [inline external-crates/move/crates/move-compiler/src/hlir/translate.rs]: This seemed like the easiest fix, and maybe the best fix? 
Otherwise we would have to a lot of massaging for `make_binders` and `bind_value_in_block`. And since we must already be in an error, might as well keep propagating

Comment (cgswords) [inline external-crates/move/crates/move-compiler/src/hlir/translate.rs]: 😢 I see _why_ but damn this is awful. Is this any better?
```
  let error_ty = error_single_type(a.loc);
  let a_ty = rvalue.ty.value.type_at_index(idx).unwrap_or_else(|| {
      debug_assert!(context.env.has_errors());
      &error_ty
  });
```

Comment (cgswords) [reply external-crates/move/crates/move-compiler/src/hlir/translate.rs]: We could also consider just bailing here, putting nothing else on the block (or an error expression) and returning from this function. It might miss some further errors that calling `assign` on the subsequent argument will turn up, but at this point the program already has errors and it's already a mess.

File: external-crates/move/crates/move-compiler/src/naming/translate.rs (hunk 1 above)
Comment (cgswords) [reply external-crates/move/crates/move-compiler/src/naming/translate.rs:4042]: Is there a test case to trip this ICE?

File: external-crates/move/crates/move-compiler/src/hlir/translate.rs (hunk 2 above)
Comment (tnowacki) [reply external-crates/move/crates/move-compiler/src/hlir/translate.rs]: I can do that if you want, sure.
