### PR TITLE
Delete async when new wallet context in sui sdk

### LINKED ISSUE #16458: Please delete async when new wallet context in sui-sdk
## Steps to Reproduce Issue
The `WalletContext::new` method does not require any asynchronous functions, thus it does not need to be defined as an asynchronous function.

https://github.com/MystenLabs/sui/blob/d54ac2f4e1fc1cda0a846bc1fea679a9ff45882e/crates/sui-sdk/src/wallet_context.rs#L32
```
pub async fn new(
    config_path: &Path,
    request_timeout: Option<std::time::Duration>,
    max_concurrent_requests: Option<u64>,
) -> Result<Self, anyhow::Error> {
    let config: SuiClientConfig = PersistedConfig::read(config_path).map_err(|err| {
        anyhow!(
            "Cannot open wallet config file at {:?}. Err: {err}",
            config_path
        )
    })?;

    let config = config.persisted(config_path);
    let context = Self {
        config,
        request_timeout,
        client: Default::default(),
        max_concurrent_requests,
    };
    Ok(context)
}
```

## Expected Result
Delete async when new one wallet context.

```
pub fn new(
    config_path: &Path,
    request_timeout: Option<std::time::Duration>,
    max_concurrent_requests: Option<u64>,
) -> Result<Self, anyhow::Error> {
    let config: SuiClientConfig = PersistedConfig::read(config_path).map_err(|err| {
        anyhow!(
            "Cannot open wallet config file at {:?}. Err: {err}",
            config_path
        )
    })?;

    let config = config.persisted(config_path);
    let context = Self {
        config,
        request_timeout,
        client: Default::default(),
        max_concurrent_requests,
    };
    Ok(context)
}
```

### PR DESCRIPTION
**Pull request by ccbond**
## Description 

Fix #16458 

## Test Plan 

---
If your changes are not user-facing and do not break anything, you can skip the following section. Otherwise, please briefly describe what has changed under the Release Notes section.

### Type of Change (Check all that apply)

- [ ] protocol change
- [ ] user-visible impact
- [x] breaking change for a client SDKs
- [ ] breaking change for FNs (FN binary must upgrade)
- [ ] breaking change for validators or node operators (must upgrade binaries)
- [ ] breaking change for on-chain data layout
- [ ] necessitate either a data wipe or data migration

### Release notes
The `WalletContext::new` method does not have any asynchronous dependencies, and thus it does not need to be defined as an asynchronous function. This PR is a breaking change that modifies the signature of `WalletContext::new` into a synchronous function. Users that depend on `WalletContext::new` will need to update callsites accordingly by dropping the `.await`.

### CODE REVIEW

**Comment by wlmyng** [comment]
@ccbond thanks for taking a stab at this. Now that `WalletContext::new` is no longer `async`, we also need to remove all instances of `.await` from the codebase. cc: @stefan-mysten

**Comment by ccbond** [comment]
@wlmyng  i use global find all functions use ```WalletContext::new()```,  judgment and delete all useless async define. Maybe you can help me review this pr.

**Comment by wlmyng** [comment]
@ccbond  thanks for cleaning up some of the issues! It should be mostly clerical work at this point - do you mind taking a look at the errors from ci and cleaning those up as well?

**Comment by ccbond** [comment]
of course. @wlmyng  thanks for your review.

File: crates/sui-cluster-test/src/faucet.rs [hunk 1]
```diff
@@ -30,8 +30,7 @@ impl FaucetClientFactory {
                     .expect("Expect local faucet key for local cluster")
                     .copy();
                 let wallet_context = new_wallet_context_from_cluster(cluster, key)
-                    .instrument(info_span!("init_wallet_context_for_faucet"))
-                    .await;
+                    .instrument(info_span!("init_wallet_context_for_faucet")).await;
```
Comment (wlmyng) [inline crates/sui-cluster-test/src/faucet.rs]: i think we can drop the await here since the function is not async anymore

File: crates/sui-cluster-test/src/wallet_client.rs [hunk 2]
```diff
@@ -25,8 +25,7 @@ impl WalletClient {
         let key = cluster.user_key();
         let address: SuiAddress = key.public().into();
         let wallet_context = new_wallet_context_from_cluster(cluster, key)
-            .instrument(info_span!("init_wallet_context_for_test_user"))
-            .await;
+            .instrument(info_span!("init_wallet_context_for_test_user")).await;
```
Comment (wlmyng) [inline crates/sui-cluster-test/src/wallet_client.rs]: i think we can drop the await here since the function is not async anymore

**Review by wlmyng — COMMENTED** [review]
I believe there's still a few spots to clean up. Would you also be able to pull from main to pick up the `pnpm audit` fix?

File: crates/sui-cluster-test/src/faucet.rs (hunk 1 above)
Comment (ccbond) [reply crates/sui-cluster-test/src/faucet.rs]: yes, i think i can ues ```let wallet_context = new_wallet_context_from_cluster(cluster, key);``` directly.

File: crates/sui-cluster-test/src/wallet_client.rs (hunk 2 above)
Comment (ccbond) [reply crates/sui-cluster-test/src/wallet_client.rs]: ues ```let wallet_context = new_wallet_context_from_cluster(cluster, key);``` directly.

**Comment by ccbond** [comment]
> I believe there's still a few spots to clean up. Would you also be able to pull from main to pick up the `pnpm audit` fix?

When i run `pnpm audit`, i got
 
image

image

image

i  can't  get any valid info. It seems that there is no information related to my PR, did I miss something?

**Comment by wlmyng** [comment]
@ccbond i just meant that you can pull latest from main to pick up the fix for the `pnpm audit` bit - the fix is upstream, not something you need to worry about

**Comment by ccbond** [comment]
> @ccbond i just meant that you can pull latest from main to pick up the fix for the `pnpm audit` bit - the fix is upstream, not something you need to worry about

oh, i got it.

**Comment by ccbond** [comment]
All the previous tests passed, so I pull rebase the latest code but its needed to approve the tests again. @wlmyng

**Review by wlmyng — APPROVED** [review]
looks good!

File: crates/sui-cluster-test/src/faucet.rs [hunk 3]
```diff
@@ -29,9 +29,7 @@ impl FaucetClientFactory {
                     .local_faucet_key()
                     .expect("Expect local faucet key for local cluster")
                     .copy();
-                let wallet_context = new_wallet_context_from_cluster(cluster, key)
-                    .instrument(info_span!("init_wallet_context_for_faucet"))
```
Comment (wlmyng) [inline crates/sui-cluster-test/src/faucet.rs:33]: actually, can we add this instrument and info_span back?

File: crates/sui-cluster-test/src/wallet_client.rs [hunk 4]
```diff
@@ -24,9 +24,7 @@ impl WalletClient {
     pub async fn new_from_cluster(cluster: &(dyn Cluster + Sync + Send)) -> Self {
         let key = cluster.user_key();
         let address: SuiAddress = key.public().into();
-        let wallet_context = new_wallet_context_from_cluster(cluster, key)
```
Comment (wlmyng) [inline crates/sui-cluster-test/src/wallet_client.rs:27]: same here - makes sense to drop the `await` but we can still have the `instrument(info_span!`

**Review by wlmyng — CHANGES_REQUESTED** [review]
wanted to call out a slight change

File: crates/sui-cluster-test/src/faucet.rs (hunk 3 above)
Comment (ccbond) [reply crates/sui-cluster-test/src/faucet.rs:33]: the `new_wallet_context_from_cluster` was updated to be synchronous, does it need to do instrument tracing?
i look document, it normal use in async func..  Just curious.

**Comment by ccbond** [comment]
@wlmyng  Is there anything else I can change？

**Review by wlmyng — APPROVED** [review]
Looks good - let's ship this

**Comment by stefan-mysten** [comment]
Thanks for being persistent with this change @ccbond! 
@wlmyng feel free to merge it!
