### PR TITLE
[ts-sdk] RPC validation error fix

### LINKED ISSUE #12061: RpcValidation Error, Could I turn on skipDataValidation?
## Steps to Reproduce Issue

Fill this in with the concrete steps needed to reproduce the bug. When providing code in the reproduction steps, use the smallest snippet of code that demonstrates the issue, removing any extraneous details.

e.g.
1. Call function <function call>.

await provider.getTransactionBlock({
      digest: tx,
      options: {
        showInput: true,
        showEffects: true,
        showEvents: true,
        showObjectChanges: true,
        showBalanceChanges: true,
      },
    });

3. Use return value and call <other function call>.

RPCValidationError: Error: RPC Validation Error: The response returned from RPC server does not match the TypeScript definition. This is likely because the SDK version is not compatible with the RPC server.
Cause: StructError: At path: transaction.data.transaction -- Expected the value to satisfy a union of object | object | object | object, but received: [object Object]
Reponse Received: {
 "digest": "3dvgcG2CbvZDFY1fBDsabfc3zquJvhJiJNMTt7BEs3pF",

Specify what outcome you expected should have resulted, but didn't.

It works well but i don't want to see error warning. Also i wrote this problem in forum.

* OS: <specify OS version>.  more than m5.4xlarge ubuntu 20.04 lts 
* Compiler: <specify compiler version> latest

### PR DESCRIPTION
**Pull request by Jordan-Mysten**
## Description

This resolves an issue where we hit RPC validation warnings for some users. Fixes #12061.

## Test Plan

Ran locally.

---
If your changes are not user-facing and not a breaking change, you can skip the following section. Otherwise, please indicate what changed, and then add to the Release Notes section as highlighted during the release process.

### Type of Change (Check all that apply)

- [ ] user-visible impact
- [ ] breaking change for a client SDKs
- [ ] breaking change for FNs (FN binary must upgrade)
- [ ] breaking change for validators or node operators (must upgrade binaries)
- [ ] breaking change for on-chain data layout
- [ ] necessitate either a data wipe or data migration

### CODE REVIEW

File: sdk/typescript/src/types/transactions.ts [hunk 1]
```diff
@@ -168,7 +168,7 @@ export const SuiTransactionBlockData = object({
   messageVersion: literal('v1'),
   transaction: SuiTransactionBlockKind,
   sender: SuiAddress,
-  gasData: SuiGasData, // this shit is diff bw wallet and explorer
```
Comment (williamrobertson13) [inline sdk/typescript/src/types/transactions.ts:171]: lol

**Review by williamrobertson13 — APPROVED** [review]
