### PR TITLE
Disable `--test` flag when publishing package using Sui client

### LINKED ISSUE #13679: Error when publishing packages via` sui client publish--test`
There seems to be a problem with publishing packages with `sui client` using the `--test` flag. Below is an MRE.
I have searched this repository's issue list for similar issues mentioning `friend/public(friend)` or `--test`, but was unable to find anything related.

## Steps to Reproduce Issue
1. Create a new package via `sui move new friend_test`
2. Create two new files, one in `sources` and another in a new directory called `tests`, such that
```bash
$ tree
.
├── Move.lock
├── Move.toml
├── sources
│   └── main.move
└── tests
    └── test.move
```
3. Insert the following content into `main.move`
```rust
module friend_test::main {
    friend friend_test::test;

    public(friend) fun foo(): u64 {
        5
    }
}
```
4. Insert the following content into `test.move`
```rust
#[test_only]
module friend_test::test {
    use friend_test::main;

    #[test]
    fun boo() {
        main::foo();
    }
}
```
5. Publish the package with an appropriately funded account on e.g. localnet, devnet, testnet:
```bash
sui client publish --test  --skip-dependency-verification --gas-budget 10000000  ./friend_test
```
Note the required `--test` flag because `friend_test::test` uses a `public(friend)` function from `friend_test::main`.

## Expected Result

The package should be published, with output similar to the below (as of `sui` version `1.9.0`)

```bash
----- Transaction Digest ----
...
----- Transaction Data ----
...
----- Transaction Effects ----
Status : Success
...
----- Events ----
Array []
----- Object changes ----
Array [
    Object {
        ...
        Object {
        "type": String("created"),
        ...
        "objectType": String("0x2::package::UpgradeCap"),
    },
    Object {
        "type": String("published"),
        ...
        "modules": Array [
            String("main"),
        ],
    },
]
----- Balance changes ----
...
```

## Actual Result

The following error is shown as a result:

```bash
Error executing transaction: Failure {
    error: "VMVerificationOrDeserializationError in command 0",
}
```

## System Information

* OS: ` Ubuntu 20.04.6 LTS` (WSL)
* Compiler:
```bash
$ rustc --version
rustc 1.72.0 (5680fa18f 2023-08-23)
$ sui --version
sui 1.9.0-f598b13b7
```

### PR DESCRIPTION
**Pull request by rockbmb**
## Description 

This PR disables the use of the `--test` flag when executing `sui client publish`.
It closes #13679, following discussion in that thread.

## Test Plan 

I've added a test to `./crates/sui/tests/cli_tests.rs` that verifies the `--test` flag will no longer be accepted with `client publish`, along with an error message explaining why.

---

### Type of Change (Check all that apply)

- [ ] protocol change
- [x] user-visible impact
- [ ] breaking change for a client SDKs
- [ ] breaking change for FNs (FN binary must upgrade)
- [ ] breaking change for validators or node operators (must upgrade binaries)
- [ ] breaking change for on-chain data layout
- [ ] necessitate either a data wipe or data migration

### Release notes

* Added an error message to Sui CLI when trying to publish a package via `sui client publish`, and the package requires compilation in test mode

### CODE REVIEW

**Comment by rockbmb** [comment]
@tzakian Hey, two questions
1. I can't add you as a reviewer, could you kindly do so for me, please?
2. Regarding the `Release notes` section of the PR description I have to fill out, is there anything in particular I should write?

Thanks!

**Comment by tzakian** [comment]
Thank you for the PR @rockbmb! I will take a look at this and may add some other reviewers as well :) 

In terms of release notes just describing what this prevents is good enough (and will get picked up). E.g., "Added error to Sui CLI when trying to publish a package compiled in test mode"

File: crates/sui/src/client_commands.rs [hunk 1]
```diff
@@ -732,6 +732,17 @@ impl SuiClientCommands {
                 serialize_signed_transaction,
                 lint,
             } => {
+                if build_config.test_mode {
```
Comment (rockbmb) [inline crates/sui/src/client_commands.rs:735]: While the solution presented in this PR works, a user running `sui client publish --help` will still see `--test` in the list of available flags.

In order to remove this entirely, I can see two solutions:
1. [`BuildConfig`](https://github.com/MystenLabs/sui/blob/main/external-crates/move/tools/move-package/src/lib.rs#L36) is duplicated into a `struct` without a `test_mode` field, and used here
2. The `test_mode` flag is extracted into a different structure `BuildConfigNoTest` that two fields: it, and athe original `BuildConfig`

Both feel like overengineering, so I chose this approach instead.

Comment (tzakian) [reply crates/sui/src/client_commands.rs:735]: This makes sense to me as well -- agreed that the other options feel a bit like overengineering as well.

File: crates/sui/src/client_commands.rs [hunk 2]
```diff
@@ -732,6 +732,17 @@ impl SuiClientCommands {
...
+                    return Err(SuiError::ModulePublishFailure {
+                        error: "The `publish` subcommand should not be used with the `--test` flag\n\
+                                \n\
+                                Library code in published packages must not depend on test code.\n\
```
Comment (tzakian) [inline crates/sui/src/client_commands.rs:739]: Nit: 
```suggestion
                                Code in published packages must not depend on test code.\n\
```

File: crates/sui/src/client_commands.rs [hunk 3]
```diff
@@ -732,6 +732,17 @@ impl SuiClientCommands {
...
+                                In order to fix this and publish the package without `--test`, search for, and remove \
+                                instances of e.g. test modules declared as `friend`s of modules from `sources/`.".to_string(),
```
Comment (tzakian) [inline crates/sui/src/client_commands.rs:741]: I would most likely rephrase the last part of this a bit as the way tests can be defined (and how modules could depend on other test-only code) can differ, e.g., you can have test-only modules under `sources/`, and even though this is an example at the end I worry it may put blinders on folks and how they look at fixing this issue.

What do you think of maybe something like:
```
In order to fix this and publish the package without `--test` remove any non-test dependencies on test-only code. You can ensure all test-only dependencies have been removed by compiling the package normally with `sui move build`. 
```

**Review by tzakian — COMMENTED** [review]
Thanks for the PR (and thank you for the additional test too!).

Only minor nit is on the exact wording of the error message and removing the example, but otherwise this looks great to me! Once that's fixed I think this can go in.

File: crates/sui/src/client_commands.rs (hunk 3 above)
Comment (rockbmb) [reply crates/sui/src/client_commands.rs:741]: Sounds good to me.

**Review by tzakian — APPROVED** [review]
This looks good to me. Thank you for the fix, and following up with the changes!
