### PR TITLE
sui-move: drop duplicate `--path` options

### LINKED ISSUE #20003: [sui-move] duplicate `--path` options
Multiple options with the same alias make program panic in debug build, however there is no debug assertion in release build, so the product works well now.

We can use `default_value_if("package_path", builder::ArgPredicate::IsPresent, Some("true"))` to set up the option to follow the other option without using a conflict alias name.

I am happy to make a PR on it, if this looks good from your end.

## Steps to Reproduce Issue
Build `sui-move` in debug and call it directly
`cargo run --bin sui-move`

## Expected Result
Program works or return without panic.

## Actual Result
thread 'main' panicked at ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/clap_builder-4.5.2/src/builder/debug_asserts.rs:97:17:
Command sui-move: Long option names must be unique for each argument, but '--path' is in use by both 'package_path' and 'run_bytecode_verifier'
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

## System Information
* OS: NixOS
* Compiler: stable-1.81.0

### Code Snippet
https://github.com/MystenLabs/sui/blob/6b690129928ba7ae454a6c5962fca7ceb5613bed/crates/sui-move/src/main.rs#L26-L33

### PR DESCRIPTION
**Pull request by yanganto**
## Description 

Use `default_value_if` to instead of using the same alias, and avoid to have panic in debug build.
Fix #20003 

## Test plan 

Reuse existing test cases

---

## Release notes

Check each box that your changes affect. If none of the boxes relate to your changes, release notes aren't required.

For each box you select, include information after the relevant heading that describes the impact of your changes that a user might notice and any actions they must take to implement updates. 

- [ ] Protocol: 
- [ ] Nodes (Validators and Full nodes): 
- [ ] Indexer: 
- [ ] JSON-RPC: 
- [ ] GraphQL: 
- [X] CLI: add `--run-bytecode-verifier` and `--print-diags-to-stderr` for `sui-move`
- [ ] Rust SDK:
- [ ] REST API:

### CODE REVIEW

File: crates/sui-move/src/main.rs [hunk 1]
```diff
@@ -26,10 +26,18 @@ struct Args {
     #[clap(long = "path", short = 'p', global = true)]
     pub package_path: Option<PathBuf>,
     /// If true, run the Move bytecode verifier on the bytecode from a successful build
-    #[clap(long = "path", short = 'p', global = true)]
+    #[clap(
+        long,
+        default_value_if("package_path", builder::ArgPredicate::IsPresent, Some("true")),
```
Comment (stefan-mysten) [inline crates/sui-move/src/main.rs:31]:
```suggestion
        
```
I don't think this condition is really needed. The way I understand this flag is that it should be set to `global` true regardless of `package_path` option.

File: crates/sui-move/src/main.rs [hunk 2]
```diff
@@ -26,10 +26,18 @@ struct Args {
...
+        global = true
+    )]
     pub run_bytecode_verifier: bool,
     /// If true, print build diagnostics to stderr--no printing if false
-    #[clap(long = "path", short = 'p', global = true)]
+    #[clap(
+        long,
+        default_value_if("package_path", builder::ArgPredicate::IsPresent, Some("true")),
```
Comment (stefan-mysten) [inline crates/sui-move/src/main.rs:38]: Same as above
```suggestion
        
```

**Review by stefan-mysten — CHANGES_REQUESTED** [review]
Thanks for looking into this. I am not fully sure these flags require the `default_value_if`.

**Comment by stefan-mysten** [comment]
This looks good, thanks @yanganto!
